volumes:
  postgres-data:

services:
  postgresql:
    image: postgres:17.2@sha256:3267c505060a0052e5aa6e5175a7b41ab6b04da2f8c4540fc6e98a37210aa2d3
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./migrate/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    ports:
      - "80:${APP_PORT}"
    depends_on:
      - postgresql
    env_file:
      - .env
