volumes:
  postgres-data:

services:
  postgresql:
    image: postgres:17.2
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./migrate/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    image: azamatbayramov/shortly:latest
    ports:
      - "80:${APP_PORT}"
    depends_on:
      - postgresql
    env_file:
      - .env
